//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clansty.tianlang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clansty.tianlang.Common.Strs", typeof(Strs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 加群申请已同意:  的本地化字符串。
        /// </summary>
        internal static string AddAccepted {
            get {
                return ResourceManager.GetString("AddAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加群申请已拒绝:  的本地化字符串。
        /// </summary>
        internal static string AddRejected {
            get {
                return ResourceManager.GetString("AddRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此人已存在 的本地化字符串。
        /// </summary>
        internal static string AddReqOccupied {
            get {
                return ResourceManager.GetString("AddReqOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑名单用户 的本地化字符串。
        /// </summary>
        internal static string Blacklisted {
            get {
                return ResourceManager.GetString("Blacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令找不到 的本地化字符串。
        /// </summary>
        internal static string CmdNotFound {
            get {
                return ResourceManager.GetString("CmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年级格式错误 的本地化字符串。
        /// </summary>
        internal static string EnrFormatErr {
            get {
                return ResourceManager.GetString("EnrFormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此年级不支持自动审核 的本地化字符串。
        /// </summary>
        internal static string EnrUnsupported {
            get {
                return ResourceManager.GetString("EnrUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误 的本地化字符串。
        /// </summary>
        internal static string FormatErr {
            get {
                return ResourceManager.GetString("FormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请按正确格式填写 的本地化字符串。
        /// </summary>
        internal static string FormatIncorrect {
            get {
                return ResourceManager.GetString("FormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看起来你还没有加入十中大群的说
        ///加入苏州十中跨年级大群 646751705，解锁更多好玩的 的本地化字符串。
        /// </summary>
        internal static string InviteMajor {
            get {
                return ResourceManager.GetString("InviteMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此身份已有一个账户加入，如有疑问请联系管理员 的本地化字符串。
        /// </summary>
        internal static string JoinChkOccupied {
            get {
                return ResourceManager.GetString("JoinChkOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧人补填姓名成功 的本地化字符串。
        /// </summary>
        internal static string NameFillInSucceeded {
            get {
                return ResourceManager.GetString("NameFillInSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只要姓名就行，不需要别的东西 的本地化字符串。
        /// </summary>
        internal static string NameVerifyFailed {
            get {
                return ResourceManager.GetString("NameVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此身份已有一个账户加入，如有疑问请联系管理员 的本地化字符串。
        /// </summary>
        internal static string Occupied {
            get {
                return ResourceManager.GetString("Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查无此人 的本地化字符串。
        /// </summary>
        internal static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查无此人，请检查姓名是否与入学登记的姓名一致 的本地化字符串。
        /// </summary>
        internal static string RnNotFound {
            get {
                return ResourceManager.GetString("RnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此身份已有一个账号加入，我们暂时不欢迎小号加入，这是防止家长入群的必要措施。如有疑问请联系管理员 的本地化字符串。
        /// </summary>
        internal static string RnOccupied {
            get {
                return ResourceManager.GetString("RnOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实名认证成功 的本地化字符串。
        /// </summary>
        internal static string RnOK {
            get {
                return ResourceManager.GetString("RnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经实名认证了，无需再次填写姓名 的本地化字符串。
        /// </summary>
        internal static string RnVerified {
            get {
                return ResourceManager.GetString("RnVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好，我是甜狼，本群的人工智能管理 的本地化字符串。
        /// </summary>
        internal static string SetupGreetingIntr {
            get {
                return ResourceManager.GetString("SetupGreetingIntr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前我们需要的信息就这么多，祝你在群里玩的开心 的本地化字符串。
        /// </summary>
        internal static string SetupOK {
            get {
                return ResourceManager.GetString("SetupOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的群名片已修改为  的本地化字符串。
        /// </summary>
        internal static string SetupSetNC {
            get {
                return ResourceManager.GetString("SetupSetNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请回复你开学后的年级或毕业的年份
        ///例如 高一, 初三, 2019届, 2019届初中, 2019届初中/高一 的本地化字符串。
        /// </summary>
        internal static string SetupStep2 {
            get {
                return ResourceManager.GetString("SetupStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复格式不正确，必须包含年级哦 的本地化字符串。
        /// </summary>
        internal static string SetupStep2Err {
            get {
                return ResourceManager.GetString("SetupStep2Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玄学错误，请联系管理员。 的本地化字符串。
        /// </summary>
        internal static string UnexceptedErr {
            get {
                return ResourceManager.GetString("UnexceptedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已实名用户 的本地化字符串。
        /// </summary>
        internal static string VerifiedUser {
            get {
                return ResourceManager.GetString("VerifiedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库存在此人信息，新人向导跳过 的本地化字符串。
        /// </summary>
        internal static string WizardSkip {
            get {
                return ResourceManager.GetString("WizardSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的信息 的本地化字符串。
        /// </summary>
        internal static string YourInfo {
            get {
                return ResourceManager.GetString("YourInfo", resourceCulture);
            }
        }
    }
}
