//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clansty.tianlang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clansty.tianlang.Common.Strs", typeof(Strs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 只要姓名就行，不需要别的东西 的本地化字符串。
        /// </summary>
        internal static string NameVerifyFailed {
            get {
                return ResourceManager.GetString("NameVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好，我是甜狼，本群的人工智能管理 的本地化字符串。
        /// </summary>
        internal static string SetupGreetingIntr {
            get {
                return ResourceManager.GetString("SetupGreetingIntr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前我们需要的信息就这么多，祝你在群里玩的开心 的本地化字符串。
        /// </summary>
        internal static string SetupOK {
            get {
                return ResourceManager.GetString("SetupOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的群名片已修改为 {0} 的本地化字符串。
        /// </summary>
        internal static string SetupSetNC {
            get {
                return ResourceManager.GetString("SetupSetNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请回复你开学后的年级或毕业的年份
        ///例如 高一, 初三, 2019届, 2019届初中, 2019届初中/高一 的本地化字符串。
        /// </summary>
        internal static string SetupStep2 {
            get {
                return ResourceManager.GetString("SetupStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复格式不正确，必须包含年级哦 的本地化字符串。
        /// </summary>
        internal static string SetupStep2Err {
            get {
                return ResourceManager.GetString("SetupStep2Err", resourceCulture);
            }
        }
    }
}
